[language-server.terraform-ls]
command = "terraform-ls"
args = ["serve"]

[language-server.oxfmt]
command = "oxfmt"
args = ["--lsp"]
required-root-patterns = [ ".oxfmtrc.json" ]

[language-server.oxlint]
command = "oxlint"
args = ["--lsp"]
required-root-patterns = [ ".oxlintrc.json" ]

[language-server.efm-lsp-prettier]
command = "efm-langserver"
documentFormatting = true

[[language]]
name = "typescript"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [ "format" ] },
  { name = "oxlint", except-features = [ "format" ] },
  { name = "oxfmt", only-features = [ "format" ] },
  { name = "efm-lsp-prettier", only-features = [ "format" ] }
]

[[language]]
name = "tsx"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [ "format" ] },
  { name = "oxlint", except-features = [ "format" ] },
  { name = "oxfmt", only-features = [ "format" ] },
  { name = "efm-lsp-prettier", only-features = [ "format" ] }
]

[[language]]
name = "javascript"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [ "format" ] },
  { name = "oxlint", except-features = [ "format" ] },
  { name = "oxfmt", only-features = [ "format" ] },
  { name = "efm-lsp-prettier", only-features = [ "format" ] }
]

[[language]]
name = "jsx"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [ "format" ] },
  { name = "oxlint", except-features = [ "format" ] },
  { name = "oxfmt", only-features = [ "format" ] },
  { name = "efm-lsp-prettier", only-features = [ "format" ] }
]

[[language]]
name = "json"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [ "format" ] },
  { name = "oxlint", except-features = [ "format" ] },
  { name = "oxfmt", only-features = [ "format" ] },
  { name = "efm-lsp-prettier", only-features = [ "format" ] }
]

[[language]]
name = "css"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [ "format" ] },
  { name = "oxlint", except-features = [ "format" ] },
  { name = "oxfmt", only-features = [ "format" ] },
  { name = "efm-lsp-prettier", only-features = [ "format" ] }
]

[[language]]
name = "html"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [ "format" ] },
  { name = "oxlint", except-features = [ "format" ] },
  { name = "oxfmt", only-features = [ "format" ] },
  { name = "efm-lsp-prettier", only-features = [ "format" ] }
]

[[language]]
name = "markdown"
auto-format = true
language-servers = [
  { name = "oxlint", except-features = [ "format" ] },
  { name = "oxfmt", only-features = [ "format" ] }
]
text-width = 120

[[language]]
name = "rust"
language-servers = [ { name = "rust-analyzer" } ]

[[language]]
name = "hcl"
language-servers = [ "terraform-ls" ]
language-id = "terraform"

[[language]]
name = "tfvars"
language-servers = [ "terraform-ls" ]
language-id = "terraform-vars"

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "sql"
indent = { tab-width = 2, unit = " " }
